### ISSUE TITLE
Research 3rd party solutions

### ISSUE THREAD

**Issue by pitchinvasion** [makersacademy/careers#1]
* ATS - [loads here](http://www.softwareadvice.com/uk/hr/) - workable
* CRM systems - bullhorn, pipedrive, salesforce, greenhorn
* Automated contact solutions eg mandrill

**Comment by spike01** [comment]
Waiting for replies and to arrange meetings with Salesforce, Bullhorn and Workable. Greenhouse eliminated for being not suitable.

**Comment by spike01** [comment]
Meeting Bullhorn on Tuesday 11am

**Comment by spike01** [comment]
Going to trial Bullhorn when Will returns from the land of the rising sun
