### ISSUE TITLE
Lunchtime talk slack reminders

### ISSUE THREAD

**Issue by pitchinvasion** [makersacademy/careers#3]
- Several reminders/confirmations to speaker, staff and students/grads

**Comment by pitchinvasion** [comment]
Calendar sends an automatic slack notification - could use Zapier to automatically fire slack messages at the write time to the right channels.

- Staff notification goes to #general
- Student notifications go to #general and #alumni? 

@isoworg needs to confirm those details

**Comment by spike01** [comment]
![notification_automation_wireframe](https://cloud.githubusercontent.com/assets/7307631/9759603/18d46f98-56e6-11e5-88b5-b66f8e01715e.jpg)

**Comment by pitchinvasion** [comment]
events calendar

**Comment by silvabox** [comment]
This now posts to the webhook applications.makersacademy.com/careers/lunchtime_talks/notification which creates notifications in makers #general and student #general and #alumni channels.  Calendar event summary must include the text `LUNCHTIME TALK`.   Notifications are 5 days, 2 days, 2 hours and 10 minutes before.  The slack post will include the calendar event *description*.  QA will be when the first talk is correctly notified!
